apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: {{ prefix-name }}-{{ suffix-name }}
  labels:
    p6m.dev/app: {{ prefix-name }}-{{ suffix-name }}
spec:
  config:
    GRPC_PORT: "8080"  # Service Port
    SERVER_PORT: "8081" # Management Port
    LOGGING_STRUCTURED: "true"
    ConnectionStrings__DefaultConnection: "Host=$(postgres_dotnet_grpc_service_db_endpoint);Port=$(postgres_dotnet_grpc_service_db_port);Database=dotnet_grpc_service_db;Username=$(postgres_dotnet_grpc_service_db_username);Password=$(postgres_dotnet_grpc_service_db_password);sslmode=require"
  resources: 
    postgres:
      - name: {{ prefix-name }}-{{ suffix-name }}
  deployment:
    image: {{ prefix-name }}-{{ suffix-name }}-server:latest
    ports:
      - protocol: grpc
        port: 8080
      - protocol: http
        port: 8081
    readinessProbe:
      port: 8081
      path: /health
  networking:
    inbound:
      services:
        - name: dotnet-grpc-domain-gateway
          namespace: dotnet-grpc-domain-gateway
          port: 8080